version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/shared"
    schedule:
      interval: "daily"